add verification script
SuryaKrishna02/maya-dataset-creation pull request #6
Opened 2024-08-08 06:48 UTC by asusevski

Resolve gh issue Verification Script #4

2024-08-08 12:27 UTC, SuryaKrishna02 requested changes
Could you please update the `requirements.txt` file with all the libraries used in the verification script?

2024-08-09 04:23 UTC, asusevski commented
Resolved all issues I believe, please review :)

2024-08-09 17:01 UTC, SuryaKrishna02 requested changes

2024-08-09 17:01 UTC, SuryaKrishna02 commented on translation/verification.py
> +            response = translate(co, prediction, "en")
```suggestion
            response = translate(co, prediction, "English")
```
Giving language code in the prompt might confuse the model. So, I think spelled out language is better.

2024-08-10 19:30 UTC, asusevski commented
I added the requested changes + added to constants.py a map from iso lang code to a verbose spelling of the language for llm consumption 👍

2024-08-11 02:49 UTC, SuryaKrishna02 approved these changes
LGTM! Thanks @asusevski for your great work!!

2024-08-11 02:50 UTC, merged