Evaluation script added
SuryaKrishna02/maya-dataset-creation pull request #9
Opened 2024-08-17 20:54 UTC by pilot-j

### Evaluation Script: Prompt Quality Assessment

Use `eval_script.py` to evaluate the quality of responses based on custom prompts.

**Arguments**:
- `--base_path`: Directory for output CSV reports.
- `--eval_csv`: Path to the evaluation metrics CSV.
- `--prompt_file`: Path to a `.txt` file containing a list of prompts.

### `Prompt` Class Description

The `Prompt` class is designed to encapsulate and structure the information needed for generating and evaluating language model prompts. It consists of three key attributes:

- **`translate_to`**: (String) Specifies the target language or action for the prompt. For example, `"Hindi"` or `"Spanish"`.

- **`preamble`**: (String) Provides the introductory text or instructions that guide the interpretation of the `message`. For example, `"Translate"` or `"Translate to Spanish"`.

- **`message`**: (String) Contains the main content or input text that needs to be processed or translated as per the `translate_to` instruction.

### Example Usage:

Given a prompt like:

```python
prompt = Prompt(translate_to="Hindi", preamble="Translate", message="Input")
```

This creates a prompt where the input text `"Input"` is instructed to be translated to Hindi. The `Prompt` class structures this data to be used effectively within the evaluation script.

**Prompt Format**:
Each prompt is a list of three strings: `translate_to`, `preamble`, and `message`, wrapped into a `Prompt` class. Example prompt file content:

```plaintext
[['Hindi', 'Translate', 'Input'], ['Spanish', 'Translate to Spanish', 'Input Text']]
```

**Output**:
Generates evaluation reports named as:

```plaintext
prompt_<prompt_no>_<language>_eval_report.csv
```

Example: `prompt_0_Hindi_eval_report.csv`

**Usage**:
```sh
python3 eval_script.py --base_path ./output_reports --eval_csv ./evaluation_dataset.csv --prompt_file ./prompts.txt
```

2024-08-17 21:46 UTC, SuryaKrishna02 requested changes
Great Work. The following are the minor changes that needs to be done:
1. Update the `requirements.txt` file.
2. Remove unused import statements.
3. Remove unneccessary arguments.
4. If possible, write the datatypes of the arguments like other files `translation/verification.py` file.

2024-08-17 21:46 UTC, SuryaKrishna02 commented on translation/eval_script.py
> +import sys
```suggestion
```

2024-08-17 21:46 UTC, SuryaKrishna02 commented on translation/eval_script.py
> +import json
```suggestion
```

2024-08-17 21:46 UTC, SuryaKrishna02 commented on translation/eval_script.py
> +import random
```suggestion
```

2024-08-17 21:46 UTC, SuryaKrishna02 commented on translation/eval_script.py
> +import numpy as np
```suggestion
```

2024-08-17 21:46 UTC, SuryaKrishna02 commented on translation/eval_script.py
> +def evaluate(lang, base_path, pair_list, prompt):
```suggestion
def evaluate(lang, pair_list, prompt):
```

2024-08-17 21:46 UTC, SuryaKrishna02 commented on translation/eval_script.py
> +      eval_list = evaluate(lang, base_path, pair_list, prompt)
```suggestion
      eval_list = evaluate(lang, pair_list, prompt)
```

2024-08-18 06:03 UTC, pilot-j commented
> Great Work. The following are the minor changes that needs to be done:
> 
> 1. Update the `requirements.txt` file.
> 2. Remove unused import statements.
> 3. Remove unneccessary arguments.
> 4. If possible, write the datatypes of the arguments like other files `translation/verification.py` file.

Did the necessary changes. Please review and let me know.

2024-08-19 20:12 UTC, SuryaKrishna02 approved these changes
LGTM. Thanks for the Great Work.

2024-08-19 20:13 UTC, merged